### ISSUE TITLE
publish on CTAN

### ISSUE THREAD

**Issue by maieul** [michal-h21/uninormalize#1]
Could you publish it on CTAN? I think it will be less confident ;-)

**Comment by michal-h21** [comment]
I could, but I should ask Arthur first, I think.

See also https://github.com/michal-h21/luatex-harfbuzz-shaper  I think
Harfbuzz does normalization by default and it has many other interesting
features.

**Comment by maieul** [comment]
If I don't make mistake, harfbuzz is the new tool used by xetex to build the output? in this case the normalization will be done only for the glyph building?
in some case we need to do it at the input, especially when you construit command name with user input \csname.

Cf https://github.com/maieul/ledmac/commit/07fda730a073f8a9e0eb58d6901dfc33c385f2d3#diff-ff864afe8a6f67c7df8f2c80291f2598R1340

yes I think it will be better to wait for Arthur answer. It seems to be now active again.

**Comment by michal-h21** [comment]
On Fri, May 15, 2015 at 9:49 PM, Maïeul Rouquette notifications@github.com
wrote:

> If I don't make mistake, harfbuzz is the new tool used by xetex to build
> the output? in this case the normalization will be done only for the glyph
> building?

yes, it is useful for Asian and Arabic scripts, where support in Luaotfload
is lacking. But it is used only for glyph building, for \csnames, input
buffer processing is needed

> in some case we need to do it at the input, especially when you construit
> command name with user input \csname.
> 
> Cf
> https://github.com/maieul/ledmac/commit/07fda730a073f8a9e0eb58d6901dfc33c385f2d3#diff-ff864afe8a6f67c7df8f2c80291f2598R1340
> 
> yes I think it will be better to wait for Arthur answer. It seems to be
> now active again.

I've just posted mail to Arthur,  I will upload the package to CTAN if he
doesn't mind

**Comment by maieul** [comment]
hi, some news?

**Comment by michal-h21** [comment]
Hi Maïeul,not really, but I think I can pack it up as it is now and just
upload it to CTAN. I don't think me or Arthur would work on it in the near
future.

On Sun, Nov 29, 2015 at 10:52 PM, Maïeul Rouquette <notifications@github.com

**Comment by maieul** [comment]
so, let's go?

**Comment by cdlm** [comment]
yup, would be nice… or if another solution is available, please advise

**Comment by michal-h21** [comment]
There are two blocks - all Lua files should be renamed to use some sort of prefix - like `uninormalize-normalize.lua`. This is needed by TeX distributions to prevent name clashes. I also think the node processing doesn't work, because it uses obsolete node types. So these issues should be fixed first.

**Comment by maieul** [comment]
some news ? @jbezos asked for it on https://github.com/latex3/babel/issues/107#issuecomment-733030879

**Comment by michal-h21** [comment]
I've just updated the code to use `char-def.lua` shipped in TL instead of the custom copy. It seems that it now contains all necessary information. Can you test that it works well?

**Comment by michal-h21** [comment]
@maieul I've fixed some remaining bugs and updated documentation. I think the code is ready to be published on CTAN now.

**Comment by maieul** [comment]
nice :)

**Comment by michal-h21** [comment]
@maieul I've uploaded it, so it should be available soon :)
